---
deployment:
  tasks:
    - export DEPLOYPATH=/home/cfbcfbae/public_html/
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R docs $DEPLOYPATH
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R adds $DEPLOYPATH